# Site settings
title: Cadmium - Natural language processing library for Crystal
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Cadmium is a natural language processing library for the Crystal
  programming language. Built in are several helpful algorithms for
  performing all sorts of NLP tasks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cadmium.ml" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cadmium_cr
github_username:  cadmiumcr

# Build settings
markdown:         kramdown
highlighter:      rouge
permalink:        /blog/:year/:month/:day/:title/

navigation_links:
  - title: "Guide"
    url: "/guide"
  - title: "API"
    url: "https://api.cadmium.ml"
  - title: "Blog"
    url: "/blog"
  - title: "Community"
    url: "https://gitter.im/cadmiumcr"

jsarr:
  - name: "/js/fontawesome-all.min.js"

plugins:
  - jekyll-feed
  - jekyll-mentions
  - jemoji
  - jekyll-seo-tag